name: INSTAGRAM DELETE SCHEDULER

on:
  workflow_dispatch:
  schedule:
    - cron: '30 4 * * *'  # Runs at 10:00 AM IST
  
jobs:
  run-script:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    steps:
      # Checkout the repository
      - name: Checkout Code
        uses: actions/checkout@v4
        with:
          repository: Paragoun/paragon
          token: ${{ secrets.PRIVATE_REPO_TOKEN }}
          sparse-checkout: |
            INSTAGRAM/
            requirements.txt
          fetch-depth: 1
          
      # Set up Python environment
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12.9'  # Specify the Python version you need

      # Install the necessary packages
      - name: Installed package list
        run: apt list --installed
        
      # Install dependencies
      - name: Install dependencies
        run: |
         python3 -m pip install --upgrade pip
         pip3 install -r requirements.txt

      # Run your Python script
      - name: Run Python script
        run: python3 INSTAGRAM/instagram_delete.py
